config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :accounts
  resources :dashboards, only: [:index]
  resources :queries
  resources :bounds, only: [:index]
  resources :integrations, only: [:index, :show] do
    resources :bounds, only: [:new, :show]
  end
end

app/models/account.rb
class Account < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :queries
  has_many :reports
  has_many :bounds
  has_many :integrations, through: :bounds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bound.rb
class Bound < ApplicationRecord
  store :setting, accessors: [:jwt_token, :oauth2_token, :oauth2_authorization, :sql_host, :sql_username, :sql_password, :sql_database]
  belongs_to :account
  belongs_to :integration
end

app/models/integration.rb
class Integration < ApplicationRecord
  extend FriendlyId
  alias_attribute :slug, :name

  friendly_id :name, use: :slugged

  enum kind: %i(oauth2 sql jwt)

  has_many :bounds
  has_many :accounts, through: :bounds
end

app/models/query.rb
class Query < ApplicationRecord
  belongs_to :account
end

app/models/report.rb
class Report < ApplicationRecord
  serialize :bounds

  belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_account!

  def normalize_friendly_id(value)
    value.to_s.parameterize(preserve_case: true)
  end
  
  protected
  def after_sign_in_path_for(resource)
    sign_in_url = new_account_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end
end

app/controllers/bounds_controller.rb
class BoundsController < ApplicationController
  def index
    @bounds = current_account.bounds
    @integrations = Integration.all
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @bounds = current_account.bounds
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_account!

  def index
    redirect_to dashboards_path if account_signed_in?
  end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  def index
  end

  def show
    @integration = Integration.friendly.find(params[:id])
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show, :edit, :update, :destroy]

  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(query_params)

    respond_to do |format|
      if @query.save
        format.html { redirect_to @query, notice: 'Query was successfully created.' }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1
  # PATCH/PUT /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to @query, notice: 'Query was successfully updated.' }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query.destroy
    respond_to do |format|
      format.html { redirect_to queries_url, notice: 'Query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_params
      params.require(:query).permit(:title, :sql, :description, :account_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bounds_helper.rb
module BoundsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/bounds/_table.html.slim
h3 Bounds
table.table.table-striped
  thead
    tr
      th Created at
      th Integration
      th Setting type
      th
  tbody
    - if @bounds.count > 0
    -else
      .jumbotron.text-center
        h1.display-5
          | You don't have bounds connections
        p.lead You must need to active integrations below

app/views/bounds/edit.html.slim
h1 Bounds#edit
p Find me in app/views/bounds/edit.html.slim

app/views/bounds/index.html.slim
=render 'bounds/table'
hr
=render 'integrations/table'

app/views/bounds/new.html.slim
h1 Bounds#new
p Find me in app/views/bounds/new.html.slim

app/views/bounds/show.html.slim
h1 Bounds#show
p Find me in app/views/bounds/show.html.slim

app/views/dashboards/index.html.slim
-unless @bounds.count > 3
  .jumbotron.text-center
    h1.display-5
      | You don't have enough bounds connections
    p.lead You must need unless 3 active bounds conecctions
    =link_to "Create bounds", bounds_path, class: "btn btn-lg btn-success"

app/views/home/index.html.slim
.jumbotron.text-center
  h1.display-4
    | Weekly TI reports automation
  p.lead Open Source platform to weekly TI Reports for github tasks, SQL Queries, Slack messages with 'bugs found' and server uptime.
  =link_to "Sign Up for free", new_account_registration_path, class: "btn btn-lg btn-success"
.row
  .col-lg-6
    h3 SQL custom queries
    p Copy and paste your custom queries for reports
  .col-lg-6
    h3 Slack integration
    p Track bugs found by your teammates
  .col-lg-6
    h3 Github integration
    p Track your team tasks (Ice Box,Do, Done)
  .col-lg-6
    h3 Uptime Robot integration
    p Track your down server
  .col-lg-6
    h3 Generate spreadsheet reports
    p Generate spreadsheet for your managers, CEO, CIO

app/views/integrations/_table.html.slim
h3 Integrations
.row
  - @integrations.each do |integration|
    .col-md-3
      =link_to integration_path(integration) do
        =image_tag integration.image_url, width: 120

app/views/integrations/index.html.slim
h1 Integrations#index
p Find me in app/views/integrations/index.html.slim

app/views/integrations/show.html.slim
.row
  .col-md-8
    .row
      .col-md-6
        =image_tag(@integration.image_url, width: 300)
      .col-md-6
        p
          h1=@integration.name
        b
          | Connection: #{@integration.kind.capitalize}
      .col-md-12
        h3 Description
        p=@integration.description

  .col-md-4
    =link_to "Activate", "", class: "btn btn-success btn-block"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4
  =link_to "Weltire", root_path, class: 'navbar-brand'
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        =link_to "Dashboard", dashboards_path, class: "nav-item nav-link"
      li.nav-item
        =link_to "Queries", "#", class: "nav-item nav-link"
      li.nav-item
        =link_to "Bounds", "#", class: "nav-item nav-link"
      li.nav-item
        =link_to "Reports", "#", class: "nav-item nav-link"

    ul.navbar-nav.flex-row.ml-md-auto.d-none.d-md-flex
      - if account_signed_in?
        li.nav-item
          =link_to 'Close Session', destroy_account_session_path, method: :destroy, class: "nav-item nav-link"
      - else
        li.nav-item
          =link_to 'Sign In', new_account_session_path, class: "nav-item nav-link"
        li.nav-item
          =link_to 'Sign Up', new_account_registration_path, class: 'btn btn-outline-warning'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Wetire - Open Source platform to weekly TI reports automation
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    p.notice
      = notice
    p.alert
      = alert
    .container
      = yield

app/views/queries/_form.html.slim
= simple_form_for(@query) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :sql
    = f.input :description
    = f.association :account

  .form-actions
    = f.button :submit

app/views/queries/edit.html.slim
h1 Editing query

== render 'form'

=> link_to 'Show', @query
'|
=< link_to 'Back', queries_path

app/views/queries/index.html.slim
h1 Listing queries

table
  thead
    tr
      th Title
      th Sql
      th Description
      th Account
      th
      th
      th

  tbody
    - @queries.each do |query|
      tr
        td = query.title
        td = query.sql
        td = query.description
        td = query.account
        td = link_to 'Show', query
        td = link_to 'Edit', edit_query_path(query)
        td = link_to 'Destroy', query, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Query', new_query_path

app/views/queries/new.html.slim
h1 New query

== render 'form'

= link_to 'Back', queries_path

app/views/queries/show.html.slim
p#notice = notice

p
  strong Title:
  = @query.title
p
  strong Sql:
  = @query.sql
p
  strong Description:
  = @query.description
p
  strong Account:
  = @query.account

=> link_to 'Edit', edit_query_path(@query)
'|
=< link_to 'Back', queries_path